import { readFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import { createStore } from './lib/media-store.mjs'

const workspaceRoot = resolve(process.env.WORKSPACE_ROOT ?? process.cwd())
const store = createStore({ workspaceRoot })

const tools = [
  {
    name: 'canvas.get_selection',
    description: 'Read the current Codex Media Canvas selection context.',
    inputSchema: { type: 'object', properties: {}, additionalProperties: false },
  },
  {
    name: 'canvas.insert_asset',
    description: 'Insert a generated local media asset onto the canvas and persist metadata.',
    inputSchema: {
      type: 'object',
      required: ['inputPath', 'mimeType', 'fileName'],
      properties: {
        inputPath: { type: 'string' },
        mimeType: { type: 'string' },
        fileName: { type: 'string' },
        type: { type: 'string', enum: ['image', 'video', 'frame', 'model3d'] },
        parentAssetId: { type: 'string' },
        prompt: { type: 'string' },
        provider: { type: 'string' },
        model: { type: 'string' },
        skillName: { type: 'string' },
        params: { type: 'object' },
        references: { type: 'array', items: { type: 'string' } },
        width: { type: 'number' },
        height: { type: 'number' },
      },
    },
  },
  {
    name: 'canvas.create_version',
    description: 'Create a new version linked to an existing parent asset.',
    inputSchema: {
      type: 'object',
      required: ['parentAssetId', 'inputPath', 'mimeType', 'fileName'],
      properties: {
        parentAssetId: { type: 'string' },
        inputPath: { type: 'string' },
        mimeType: { type: 'string' },
        fileName: { type: 'string' },
        prompt: { type: 'string' },
        provider: { type: 'string' },
        model: { type: 'string' },
        skillName: { type: 'string' },
        params: { type: 'object' },
        references: { type: 'array', items: { type: 'string' } },
        width: { type: 'number' },
        height: { type: 'number' },
      },
    },
  },
  {
    name: 'canvas.extract_video_frame',
    description: 'Record a frame asset from a local image path generated by Codex or a helper.',
    inputSchema: {
      type: 'object',
      required: ['sourceVideoAssetId', 'inputPath', 'timestampMs', 'mimeType', 'fileName'],
      properties: {
        sourceVideoAssetId: { type: 'string' },
        inputPath: { type: 'string' },
        timestampMs: { type: 'number' },
        mimeType: { type: 'string' },
        fileName: { type: 'string' },
        width: { type: 'number' },
        height: { type: 'number' },
      },
    },
  },
  {
    name: 'canvas.get_asset_metadata',
    description: 'Read all recorded Codex Media Canvas asset metadata.',
    inputSchema: { type: 'object', properties: { assetId: { type: 'string' } } },
  },
  {
    name: 'canvas.update_asset_metadata',
    description: 'Update provider/model/prompt/params or lineage metadata for an existing canvas asset.',
    inputSchema: {
      type: 'object',
      required: ['assetId', 'metadata'],
      properties: {
        assetId: { type: 'string' },
        metadata: { type: 'object' },
      },
    },
  },
  {
    name: 'canvas.claim_request',
    description: 'Claim the next queued request submitted from the canvas for Codex processing.',
    inputSchema: { type: 'object', properties: {}, additionalProperties: false },
  },
  {
    name: 'canvas.update_request',
    description: 'Update a canvas request after Codex starts, completes, or fails it.',
    inputSchema: {
      type: 'object',
      required: ['requestId'],
      properties: {
        requestId: { type: 'string' },
        status: { type: 'string' },
        result: { type: 'object' },
        error: { type: 'string' },
      },
    },
  },
]

let buffer = ''
process.stdin.setEncoding('utf8')
process.stdin.on('data', async (chunk) => {
  buffer += chunk
  let newlineIndex = buffer.indexOf('\n')
  while (newlineIndex >= 0) {
    const line = buffer.slice(0, newlineIndex).trim()
    buffer = buffer.slice(newlineIndex + 1)
    if (line) await handleMessage(line)
    newlineIndex = buffer.indexOf('\n')
  }
})

async function handleMessage(line) {
  const message = JSON.parse(line)
  try {
    if (message.method === 'initialize') {
      send({ id: message.id, result: { protocolVersion: '2024-11-05', serverInfo: { name: 'codex-media-canvas', version: '0.1.0' }, capabilities: { tools: {} } } })
      return
    }
    if (message.method === 'tools/list') {
      send({ id: message.id, result: { tools } })
      return
    }
    if (message.method === 'tools/call') {
      const result = await callTool(message.params?.name, message.params?.arguments ?? {})
      send({ id: message.id, result: { content: [{ type: 'text', text: JSON.stringify(result, null, 2) }] } })
      return
    }
    send({ id: message.id, result: {} })
  } catch (error) {
    send({ id: message.id, error: { code: -32000, message: error instanceof Error ? error.message : String(error) } })
  }
}

async function callTool(name, args) {
  if (name === 'canvas.get_selection') {
    const state = await store.readState()
    return state.selection
  }
  if (name === 'canvas.insert_asset') {
    return store.addAsset(await inputPathToAssetArgs(args))
  }
  if (name === 'canvas.create_version') {
    return store.addAsset(await inputPathToAssetArgs({ ...args, parentAssetId: args.parentAssetId }))
  }
  if (name === 'canvas.extract_video_frame') {
    return store.addAsset(
      await inputPathToAssetArgs({
        ...args,
        type: 'frame',
        parentAssetId: args.sourceVideoAssetId,
        sourceVideoAssetId: args.sourceVideoAssetId,
        timestampMs: args.timestampMs,
      }),
    )
  }
  if (name === 'canvas.get_asset_metadata') {
    const state = await store.readState()
    return args.assetId ? state.assets.find((asset) => asset.assetId === args.assetId) ?? null : state.assets
  }
  if (name === 'canvas.update_asset_metadata') {
    return store.updateAssetMetadata(args.assetId, args.metadata ?? {})
  }
  if (name === 'canvas.claim_request') {
    return { request: await store.claimRequest() }
  }
  if (name === 'canvas.update_request') {
    const { requestId, ...patch } = args
    return store.updateRequest(requestId, patch)
  }
  throw new Error(`Unknown tool: ${name}`)
}

async function inputPathToAssetArgs(args) {
  const absolutePath = resolve(workspaceRoot, args.inputPath)
  const dataBase64 = (await readFile(absolutePath)).toString('base64')
  return { ...args, dataBase64, inputPath: undefined }
}

function send(payload) {
  process.stdout.write(`${JSON.stringify({ jsonrpc: '2.0', ...payload })}\n`)
}
